Now I sent a message and I get back the following 'undefined method' error:
Feature: greeter says hello
  In order to start learning RSpec and Cucumber# Please enter the commit message for your changes. Lines starting
  As a reader of The Rspec Book# with '#' will be ignored, and an empty message aborts the commit.
  I want a greater to say Hello# On branch master
  Scenario: greater says hello # features/greater_says_hello.feature:7# (use "git pull" to merge the remote branch into yours)
    Given a greeter # features/steps_definitions/greater_steps.rb:4#
    When I send it the greet message # features/steps_definitions/greater_steps.rb:8# Changes to be committed:
      undefined method `greet' for #<CucumberGreeter:0x000000019a0708> (NoMethodError)# modified: features/steps_definitions/greater_steps.rb
      ./features/steps_definitions/greater_steps.rb:9:in `/^I send it the greet message$/'#
      features/greater_says_hello.feature:9:in `When I send it the greet message'
    Then I should see "Hello Cucumber" # features/steps_definitions/greater_steps.rb:12 Failing Scenarios: cucumber
features/greater_says_hello.feature:7 # Scenario: greater says hello 1 scenario (1 failed) 3 steps (1 failed, 1 skipped, 1 passed) 0m0.034s